version: '3.8'

services:
  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///./database.db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: audio_ai_report
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: